[methane]
critical_temperature=190.55     # units: K
critical_pressure=4.595         # units: MPa
critical_volume=0.09860         # units: L/mol
accentric_factor=0.011          # units: dimensionless
ideal_gas_constant=0.008314     # units: MPa L mol^-1 K^-1